name: Go Pipeline with Dependencies

on:
  push:
    branches:
      - melnichenko
  pull_request:
    branches:
      - melnichenko

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Или нужная вам версия Go

      - name: Get dependencies
        run: |
          go mod tidy
          go mod download

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

      - name: Run linter
        run: golangci-lint run ./...

      - name: Build the project
        run: go build -v ./...