name: Test1

on:
  push:
    branches:
      - melnichenko
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: Set version
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download
          go mod vendor
      - name: install lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint

      - name: Run linter
        run: golangci-lint run ./...

      - name: Build Project
        run: go build -v ./...